services:
  flask:
    build: ./flask
    container_name: flask
    image: flask-app:latest
    depends_on:
      - postgres
    ports:
      - "80:80"

  postgres:
    build: ./database
    container_name: postgres
    image: postgres-app:latest
    ports:
      - "5432:5432"

  webrtc:
    build: ./webrtcserver
    container_name: webrtc
    image: webrtc-app:latest
    ports:
      - "8080:8080"
