apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    name: flask
    app: st-app-flask
spec:
  type: NodePort
  selector:
    app: st-app-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001