apiVersion: v1
kind: Service
metadata:
  name: webrtc
  labels:
    name: webrtc
    app: st-app-webrtc
spec:
  type: NodePort
  selector:
    app: st-app-webrtc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002