apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-webrtc
  labels:
    name: deploy-webrtc
    app: st-app-webrtc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deploy-webrtc
      app: st-app-webrtc
  template:
    metadata:
      name: deploy-webrtc
      labels:
        name: deploy-webrtc
        app: st-app-webrtc
    spec:
      containers:
        - name: deploy-webrtc
          image: "webrtc-app:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1024Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: "0.1"